"""flag is_deleted_from_disk for file

Revision ID: 00595d527cfd
Revises: 0da1ea31e4ce
Create Date: 2024-11-28 18:22:20.411040

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00595d527cfd"
down_revision: Union[str, None] = "0da1ea31e4ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column("is_removed_from_disk", sa.Boolean, default=False, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "is_removed_from_disk")
    # ### end Alembic commands ###
